#!/bin/sh
set +e

# Extract the current branch nam
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Define the regex pattern for the ticket ID
TICKET_ID_REGEX="^[0-9]{5,8}+"

# Check if the branch name contains the ticket ID
if [[ $BRANCH_NAME =~ $TICKET_ID_REGEX ]]; then
 TICKET_ID=${BASH_REMATCH[0]}

 # Append the ticket ID to the commit message
 sed -i.bak -e "s/$/ ${TICKET_ID}/" "$1"
fi
