#!/bin/sh
set +e

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
TICKET_ID_REGEX="^CORE-[0-9]{5,8}"
COMMIT_EDIT_MSG_PATH="$1"
COMMIT_MSG=$(head -n1 "$1")

# Extract the ticket number (format: CORE-1234)
if [[ "$BRANCH_NAME" =~ (CORE-[0-9]{3,5}) ]]; then
TICKET="${BASH_REMATCH[1]}"

# If the ticket ID is not already in the commit message, prepend it.
# Don't add ticket ID for a second time, fEx. when doing fixups or amending commits
if [[ ! $COMMIT_MSG =~ $TICKET ]]; then
  # Prepend the ticket ID to the start of the 1st line
  sed -i.bak -e "1s/^/${TICKET}:/" "$COMMIT_EDIT_MSG_PATH"
fi
fi
