name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2

jobs:
  build:
    name: Set up, Build and Deploy Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Bump version
        run: |
          ./ci/version.sh minor
        env:
          GITHUB_TOKEN: ${{ secrets.BEN_PAT_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
      - run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build manifest
        run: |
          ./ci/create-build-manifest.sh

      - name: Upload build manifest
        uses: actions/upload-artifact@v3
        with:
          name: build.manifest
          path: ci/build.manifest

      - name: Build application
        run: |
          ./ci/build.sh

      - name: Publish
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          ./ci/publish.sh
