name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: 163841473800

jobs:
  build:
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Auto Version Bump
        id: auto-version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          default: minor
          skip-tag: true

      - name: Build and Publish
        uses: defra-cdp-sandpit/cdp-build-action/build@main
        with:
          version: ${{ steps.auto-version-bump.outputs.new_tag }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
