name: Publish

on:
  push:
    branches:
      - main
jobs:
  cdp-workflows:
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Versions the new release
        id: version
        uses: phips28/gh-action-bump-version@v10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: minor

      - name: CDP build and publish the docker image
        uses: defra-cdp-sandpit/cdp-build-action/build@main
        with:
          version: ${{ steps.version.outputs.newTag }}
